# Mandatory settings

name: VicsTech
paginate: 10
url: https://victorfeight.com
repository: "victorfeight/vicstech"

# Staticman comments (full configuration in staticman.yml)
staticman:
   branch: "chalk_dev"

# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
blog_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the blog page
ga_analytics: UA-102659256-1 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: false # Change to false to disable
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: victorfeight
  linkedin: # Add your LinkedIn handle
  twitter: # Add your Twitter handle
  email: vrfeight@gmail.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /blog/page:num/
permalink: /blog/:slug
sass:
   style: compressed
   sass_dir: _assets/stylesheets
